include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true            # 🧱 يفضّل استخدام const مع الـ Widgets
    prefer_const_constructors_in_immutables: true  # const داخل الـ classes
    prefer_const_literals_to_create_immutables: true # const داخل الـ Lists و Maps
    avoid_print: false                         # يسمح بـ print (اختياري)
    always_use_package_imports: true           # يستخدم import بشكل منظم
    avoid_unnecessary_containers: true         # يمنع Container ملوش لازمة
    use_key_in_widget_constructors: true       # يضيف مفاتيح للـ Widgets
    sort_child_properties_last: true           # يخلي child آخر خاصية في الـ Widget
    unnecessary_this: true                     # يمنع this لما مش ضروري
    prefer_final_fields: true                  # يخلي الفيلد final لما ينفع
